sched: Fix symbol conflict between task-rotation feature and walt
../kernel/sched/walt/walt.h:844:19: error: conflicting types for 'is_reserved'
static inline int is_reserved(int cpu)
                  ^
../kernel/sched/walt/../../../kernel/sched/sched.h:2811:20: note: previous definition is here
static inline bool is_reserved(int cpu)
                   ^